name: Go Test Suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25' # Replace with your required Go version

    - name: Install Dependencies
      run: go mod download

    - name: Run All Tests
      run: go test -v -race ./...

